services:
  db-service:
    image: postgres:17.4-alpine
    container_name: db-service
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}

    restart: unless-stopped
    ports:
      - "${DB_EXTERNAL_PORT}:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: app-service
    ports:
      - "${API_PORT}:3000"

    depends_on:
      - db-service
    restart: always

volumes:
  postgres_data:
